### ISSUE TITLE
Map not rendering

### ISSUE THREAD

**Issue by svr8** [heremaps/devrel-workshops#21]
After completing all the steps, the `trucks` are visible and any changes in the location are reflected visibly on the map. However, the roads and other features of map/terrain are not being rendered. 

## Screenshot
![ScreenShot](https://i.ibb.co/YdDtQmg/Screenshot-from-2019-12-08-01-25-27.png)

## Web App Error Log
`Access to XMLHttpRequest at 'https://3.traffic.maps.cit.api.here.com/maptile/2.1/traffictile/newest/normal.day/12/1051/1523/256/png8?xnlp=CL_JSMv3.0.17.0&app_id=zEW2lBQONss6Edln2IsF5&app_code=Z9fAW7c8_Z4KpOk5p3zxmg' from origin 'https://myfleetdashboard.azurewebsites.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by PotatoSpudowski** [comment]
Hi,

This error was fixed by using the "REST & XYZ HUB API/CLI" instead of the "JAVASCRIPT 3.1" API
