### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by deeplook** [heremaps/devrel-workshops#57]
https://github.com/heremaps/devrel-workshops/blob/master/100DaysOfCodeWithHERE/README.md gives 404s for most likely all 100 links like https://github.com/heremaps/devrel-workshops/blob/master/Day%201. This would work: https://github.com/heremaps/devrel-workshops/tree/master/100DaysOfCodeWithHERE/Day%201

**Comment by kuberaspeaking** [comment]
Thanks for pointing this out. Issue has been fixed.
Removed spaces from folder names and fixed the links in README
